// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version (devel) DO NOT EDIT.
package schemas

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	customAlias "github.com/discord-gophers/goapi-gen/internal/test/schemas/types/alias"
	"github.com/discord-gophers/goapi-gen/internal/test/schemas/types/normal"
	"github.com/discord-gophers/goapi-gen/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	AccessTokenScopes = "access_token.Scopes"
)

// Defines values for EnumInObjInArrayVal.
var (
	UnknownEnumInObjInArrayVal = EnumInObjInArrayVal{}

	EnumInObjInArrayValFirst = EnumInObjInArrayVal{"first"}

	EnumInObjInArrayValSecond = EnumInObjInArrayVal{"second"}
)

// This schema name starts with a number
type N5startsWithNumber map[string]interface{}

// AnyType1 defines model for AnyType1.
type AnyType1 interface{}

// AnyType2 represents any type.
//
// This should be an interface{}
type AnyType2 interface{}

// CustomGoType defines model for CustomGoType.
type CustomGoType normal.CustomGoType

// CustomGoTypeWithAlias defines model for CustomGoTypeWithAlias.
type CustomGoTypeWithAlias customAlias.CustomGoType

// CustomStringType defines model for CustomStringType.
type CustomStringType string

// EnumInObjInArray defines model for EnumInObjInArray.
type EnumInObjInArray []struct {
	Val *EnumInObjInArrayVal `json:"val,omitempty"`
}

// GenericObject defines model for GenericObject.
type GenericObject map[string]interface{}

// NullableProperties defines model for NullableProperties.
type NullableProperties struct {
	Optional            *string `json:"optional,omitempty"`
	OptionalAndNullable *string `json:"optionalAndNullable"`
	Required            string  `json:"required"`
	RequiredAndNullable *string `json:"requiredAndNullable"`
}

// StringInPath defines model for StringInPath.
type StringInPath string

// EnumInObjInArrayVal defines model for EnumInObjInArray.Val.
type EnumInObjInArrayVal struct {
	value string
}

func (t *EnumInObjInArrayVal) ToValue() string {
	return t.value
}
func (t EnumInObjInArrayVal) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *EnumInObjInArrayVal) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *EnumInObjInArrayVal) FromValue(value string) error {
	switch value {

	case EnumInObjInArrayValFirst.value:
		t.value = value
		return nil

	case EnumInObjInArrayValSecond.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// Issue185JSONBody defines parameters for Issue185.
type Issue185JSONBody NullableProperties

// Issue9JSONBody defines parameters for Issue9.
type Issue9JSONBody interface{}

// Issue9Params defines parameters for Issue9.
type Issue9Params struct {
	Foo string `json:"foo"`
}

// GetPr66Params defines parameters for GetPr66.
type GetPr66Params struct {
	Foo normal.CustomGoType `json:"foo"`
}

// PostPr66Params defines parameters for PostPr66.
type PostPr66Params struct {
	Bar normal.CustomGoType `json:"bar"`
}

// Issue185JSONRequestBody defines body for Issue185 for application/json ContentType.
type Issue185JSONRequestBody Issue185JSONBody

// Bind implements render.Binder.
func (Issue185JSONRequestBody) Bind(*http.Request) error {
	return nil
}

// Issue9JSONRequestBody defines body for Issue9 for application/json ContentType.
type Issue9JSONRequestBody Issue9JSONBody

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// EnsureEverythingIsReferencedJSON200Response is a constructor method for a EnsureEverythingIsReferenced response.
// A *Response is returned with the configured status code and content type from the spec.
func EnsureEverythingIsReferencedJSON200Response(body struct {
	AnyType1 *AnyType1 `json:"anyType1,omitempty"`

	// AnyType2 represents any type.
	//
	// This should be an interface{}
	AnyType2         *AnyType2         `json:"anyType2,omitempty"`
	CustomStringType *CustomStringType `foo:"bar" json:"customStringType,omitempty"`
}) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// Issue127JSON200Response is a constructor method for a Issue127 response.
// A *Response is returned with the configured status code and content type from the spec.
func Issue127JSON200Response(body GenericObject) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// Issue127XML200Response is a constructor method for a Issue127 response.
// A *Response is returned with the configured status code and content type from the spec.
func Issue127XML200Response(body GenericObject) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/xml",
	}
}

// Issue127YAML200Response is a constructor method for a Issue127 response.
// A *Response is returned with the configured status code and content type from the spec.
func Issue127YAML200Response(body GenericObject) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "text/yaml",
	}
}

// Issue127JSONDefaultResponse is a constructor method for a Issue127 response.
// A *Response is returned with the configured status code and content type from the spec.
func Issue127JSONDefaultResponse(body GenericObject) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetIssues375JSON200Response is a constructor method for a GetIssues375 response.
// A *Response is returned with the configured status code and content type from the spec.
func GetIssues375JSON200Response(body EnumInObjInArray) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetPr66JSON200Response is a constructor method for a GetPr66 response.
// A *Response is returned with the configured status code and content type from the spec.
func GetPr66JSON200Response(body CustomGoType) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// PostPr66JSON200Response is a constructor method for a PostPr66 response.
// A *Response is returned with the configured status code and content type from the spec.
func PostPr66JSON200Response(body CustomGoTypeWithAlias) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ensure-everything-is-referenced)
	EnsureEverythingIsReferenced(w http.ResponseWriter, r *http.Request) *Response

	// (GET /issues/127)
	Issue127(w http.ResponseWriter, r *http.Request) *Response

	// (GET /issues/185)
	Issue185(w http.ResponseWriter, r *http.Request) *Response

	// (GET /issues/209/${str})
	Issue209(w http.ResponseWriter, r *http.Request, str StringInPath) *Response

	// (GET /issues/30/{fallthrough})
	Issue30(w http.ResponseWriter, r *http.Request, pFallthrough string) *Response

	// (GET /issues/375)
	GetIssues375(w http.ResponseWriter, r *http.Request) *Response

	// (GET /issues/41/{1param})
	Issue41(w http.ResponseWriter, r *http.Request, n1param N5startsWithNumber) *Response

	// (GET /issues/9)
	Issue9(w http.ResponseWriter, r *http.Request, params Issue9Params) *Response

	// (GET /pr/66)
	GetPr66(w http.ResponseWriter, r *http.Request, params GetPr66Params) *Response

	// (POST /pr/66)
	PostPr66(w http.ResponseWriter, r *http.Request, params PostPr66Params) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// EnsureEverythingIsReferenced operation middleware
func (siw *ServerInterfaceWrapper) EnsureEverythingIsReferenced(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.EnsureEverythingIsReferenced(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue127 operation middleware
func (siw *ServerInterfaceWrapper) Issue127(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue127(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue185 operation middleware
func (siw *ServerInterfaceWrapper) Issue185(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue185(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue209 operation middleware
func (siw *ServerInterfaceWrapper) Issue209(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "str" -------------
	var str StringInPath

	if err := runtime.BindStyledParameter("simple", false, "str", chi.URLParam(r, "str"), &str); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "str"})
		return
	}

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue209(w, r, str)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue30 operation middleware
func (siw *ServerInterfaceWrapper) Issue30(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "fallthrough" -------------
	var pFallthrough string

	if err := runtime.BindStyledParameter("simple", false, "fallthrough", chi.URLParam(r, "fallthrough"), &pFallthrough); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "fallthrough"})
		return
	}

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue30(w, r, pFallthrough)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetIssues375 operation middleware
func (siw *ServerInterfaceWrapper) GetIssues375(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetIssues375(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue41 operation middleware
func (siw *ServerInterfaceWrapper) Issue41(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "1param" -------------
	var n1param N5startsWithNumber

	if err := runtime.BindStyledParameter("simple", false, "1param", chi.URLParam(r, "1param"), &n1param); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "1param"})
		return
	}

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue41(w, r, n1param)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Issue9 operation middleware
func (siw *ServerInterfaceWrapper) Issue9(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params Issue9Params

	// ------------- Required query parameter "foo" -------------

	if err := runtime.BindQueryParameter("form", true, true, "foo", r.URL.Query(), &params.Foo); err != nil {
		err = fmt.Errorf("invalid format for parameter foo: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "foo"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Issue9(w, r, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetPr66 operation middleware
func (siw *ServerInterfaceWrapper) GetPr66(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPr66Params

	// ------------- Required query parameter "foo" -------------

	if err := runtime.BindQueryParameter("form", true, true, "foo", r.URL.Query(), &params.Foo); err != nil {
		err = fmt.Errorf("invalid format for parameter foo: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "foo"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetPr66(w, r, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PostPr66 operation middleware
func (siw *ServerInterfaceWrapper) PostPr66(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostPr66Params

	// ------------- Required query parameter "bar" -------------

	if err := runtime.BindQueryParameter("form", true, true, "bar", r.URL.Query(), &params.Bar); err != nil {
		err = fmt.Errorf("invalid format for parameter bar: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "bar"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PostPr66(w, r, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:    "/",
		BaseRouter: chi.NewRouter(),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/ensure-everything-is-referenced", wrapper.EnsureEverythingIsReferenced)
		r.Get("/issues/127", wrapper.Issue127)
		r.Get("/issues/185", wrapper.Issue185)
		r.Get("/issues/209/${str}", wrapper.Issue209)
		r.Get("/issues/30/{fallthrough}", wrapper.Issue30)
		r.Get("/issues/375", wrapper.GetIssues375)
		r.Get("/issues/41/{1param}", wrapper.Issue41)
		r.Get("/issues/9", wrapper.Issue9)
		r.Get("/pr/66", wrapper.GetPr66)
		r.Post("/pr/66", wrapper.PostPr66)
	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYQW/bOhL+KwRbYC+y5aRt2viWLbpFFtg2aAL0EOdAi2OLjUSy5CixYOi/L4aULDuW",
	"85qXFL28XCyJHPKbb4bfDLPmmSmt0aDR8+maW+FECQguvF2iU3p5ri8E5vQuwWdOWVRG8yk/Yz6MMysw",
	"ZxtLnnBFw/SVJ1yLEviUe6QBBz8r5UDyKboKEu6zHEpBS2Nt22lKL3nTNN1gAPLuEoVD/11h/qUq5+D2",
	"0VzlyrNowmhP5oMJu1eYM8F0NEu6jcz8B2TIm4Sf6fqqtnDEp+v+7XjA3XaEObAOPDHGhK4ZLTie6ZmO",
	"CHJTFZLNgQnNlEZwC5HBuplp2utj5dGUn81VAPHQ64SvRkszwt3BHZuEq9Iah3zKlwrzaj7OTJlK5TPj",
	"5GhpbA7Op0sjrBotQacBgRZFiuAxbRlNaWWfauNKUfDmAS4i+axQkfg/ClAEFAmPv1OehY0ith51TNKO",
	"0QU5hZvJfcB3XYAVOjFCsfTRyPApnwsXlv2kq/Jcf53/ONdnzomaZiiEMh4QZyw4VBDe7kRBP6Crkk+v",
	"+UI5jzzhHjKjJb9J9tJ6IP/aDyJs1ST8M2hwKvsaJ/Q09xZfqqIQ8wIudrDsIjMhbSO8ByCSzeCZlt1a",
	"NE9vnuPp3LPrj+/68ODTFt1Z9bp/Hl7vZo+/JrBdOYX1JSVP9F5kGXg/QnMLmt7nIBy4/3S58d/vV6OY",
	"KCzOZGHmeKZ5Kzu0RTTqMyhHtFGZlF6YAQUCjywTHjxbGMfuhFOm8kx5X4VPlZbM3IFjqEoYs4sChAcm",
	"pGSCYWdLpjNNujKvlmyhViAjLFRIJMZdLsHdBWh34Hzc/Wg8GU9icEELq/iUvxlPxkc8CUocaElB+8rB",
	"CO7A1ZgrvRwpP3KwAAc6i3FdAh4QV9DSGqWRwUp59MwbhrlA1lcQlglN0pc5EAiSKc0wV36mvYWMCS2Z",
	"NkgTrKs0yOAXJa2gbc4ln/JPAeCnDb5z/61HRznhrdE+Bvl4MqGfzGgEHUALawuVhdXSH96E0PclZveA",
	"iF72+WsHCz7lr9LelY0UbcpDk3Q2x79oc0w22YBIPWa7J2oDohH/Ep7G3EqPjt8fDN3/xC0wIpVV2leW",
	"tBkkC6StMBQvz6TR/0JmHUBpkfWzwuh4IEzntC/t+syQPEbErg6Su9trrcriOUuR82kp3K009/rZC9Xi",
	"OWhoGQkLURX4G8l7IY8fZt6Hd4dFo7bAlmQfPGD3OWjWlZ60k3fWH0smHLCuXhxOuw/v2uoAHv9tZP1i",
	"pA3U1ejtVo4TvG0Cjien6eu1R9cc5OFjDtmtZ2rR98jRVQlZIXoKinrY4ePJKd/HkOz06tfDnvVT0p1e",
	"vrnZcuHNJF0vRFFg7ky1zJt9D76Bp4Ij2S3U98bJ7TbXOghVisSeSh4RGBrwVjhaSgb8ejP5FbcG7hJb",
	"YJ90p9hx+v3hxKUGsA1Om7nCd4lMqnivMqBwYg6MWr8wrjR1/FGhZ/o+V1nefvdKAjMLGg5N3lBmfwYM",
	"nHjC9RtFda+33TvRb4/S9VGIweGMvuhCtHXTootguGttbloDIX8b25G/CnDc/9HYPubk/m2xaW4ePcWn",
	"hw9voUBjPLk+FESmdGacgwyLmp6LSoIMHV+rSZGGuZE1tTwz3ft7UNNOD9DyswJXbyW+MU9L+L+tk21R",
	"2mbia6vcwTN+QBWtS09OHm8jle/6XeLMVkWxIe7VycmBw3HhTk5+B0d/6sr9IB9f9pDvwO/OtzX+5SJy",
	"YfwTQkIX639CMvAPlmajvt0dNnC4e3u9viFkoQC3HFeuaK+j0zSFlShtAcQAlfX/BwAA//+9vFJ90RMA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
